# Generated by Django 4.2.26 on 2025-11-21 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HR',
        ),
        migrations.DeleteModel(
            name='MasterUser',
        ),
        migrations.DeleteModel(
            name='TL',
        ),
        migrations.DeleteModel(
            name='TL2',
        ),
    ]
