# Generated by Django 4.2.26 on 2025-11-21 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0002_delete_hr_delete_masteruser_delete_tl_delete_tl2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True, null=True)),
                ('education_10th_percentage', models.FloatField(blank=True, null=True)),
                ('education_12th_percentage', models.FloatField(blank=True, null=True)),
                ('ug_course', models.CharField(blank=True, max_length=150, null=True)),
                ('ug_percentage', models.FloatField(blank=True, null=True)),
                ('pg_course', models.CharField(blank=True, max_length=150, null=True)),
                ('pg_percentage', models.FloatField(blank=True, null=True)),
                ('phd_topic', models.CharField(blank=True, max_length=200, null=True)),
                ('phd_percentage', models.FloatField(blank=True, null=True)),
                ('certifications', models.TextField(blank=True, null=True)),
                ('company_id', models.CharField(max_length=50, unique=True)),
                ('official_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('official_password', models.CharField(blank=True, max_length=255, null=True)),
                ('designation', models.CharField(max_length=150)),
                ('department', models.CharField(max_length=150)),
                ('passport_number', models.CharField(blank=True, max_length=50, null=True)),
                ('passport_expiry', models.DateField(blank=True, null=True)),
                ('package', models.DecimalField(decimal_places=2, help_text='Annual CTC', max_digits=10)),
                ('contract_years', models.IntegerField(default=1)),
                ('contract_start_date', models.DateField(blank=True, null=True)),
                ('contract_end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
