# Generated by Django 4.2.26 on 2025-11-21 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='passport_expiry',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='passport_number',
        ),
        migrations.AddField(
            model_name='employee',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='employees/'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='package',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
