# Generated by Django 4.2.26 on 2025-11-22 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_employee_contact_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResignedEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=255)),
                ('employee_id', models.CharField(max_length=50)),
                ('resigned_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
