# Generated by Django 4.2.26 on 2025-11-22 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_resignedemployee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resignedemployee',
            name='employee_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='resignedemployee',
            name='resigned_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
