# Generated by Django 4.2.26 on 2025-11-22 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_resignedemployee_employee_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='resigned_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
