# Generated by Django 4.2.26 on 2025-11-24 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_project_team_teamleaderassignment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='teamleaderassignment',
            name='team_leader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_leader', to='app.employee'),
        ),
        migrations.AlterField(
            model_name='teamleaderassignment',
            name='team_members',
            field=models.ManyToManyField(related_name='team_members', to='app.employee'),
        ),
    ]
