# Generated by Django 4.2.26 on 2025-11-24 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_team_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamleaderassignment',
            name='project',
        ),
        migrations.RemoveField(
            model_name='teamleaderassignment',
            name='team',
        ),
        migrations.RemoveField(
            model_name='teamleaderassignment',
            name='team_leader',
        ),
        migrations.RemoveField(
            model_name='teamleaderassignment',
            name='team_members',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
        migrations.DeleteModel(
            name='TeamLeaderAssignment',
        ),
    ]
