# Generated by Django 4.2.26 on 2025-11-24 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_teamassignment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ResignedEmployee',
        ),
    ]
