# Generated by Django 4.2.26 on 2025-11-24 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_announcement'),
    ]

    operations = [
        migrations.CreateModel(
            name='HRProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='hr_profiles/')),
                ('full_name', models.CharField(max_length=200)),
                ('employee_id', models.CharField(max_length=100, unique=True)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=20)),
                ('nationality', models.CharField(max_length=100)),
                ('marital_status', models.CharField(blank=True, max_length=50, null=True)),
                ('mobile', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=20)),
                ('designation', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('date_of_joining', models.DateField()),
                ('employment_type', models.CharField(max_length=50)),
                ('reporting_manager', models.CharField(blank=True, max_length=150, null=True)),
                ('work_location', models.CharField(max_length=150)),
                ('company_package', models.DecimalField(decimal_places=2, max_digits=12)),
                ('monthly_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('qualification', models.CharField(max_length=100)),
                ('specialization', models.CharField(blank=True, max_length=150, null=True)),
                ('university', models.CharField(max_length=150)),
                ('year_of_passing', models.CharField(max_length=10)),
                ('parent_name', models.CharField(blank=True, max_length=150, null=True)),
                ('spouse_name', models.CharField(blank=True, max_length=150, null=True)),
                ('emergency_contact_name', models.CharField(max_length=150)),
                ('emergency_contact_number', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('access_level', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
