# Generated by Django 4.2.26 on 2025-11-27 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_hr_delete_hrprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HR',
        ),
    ]
