# Generated by Django 4.2.26 on 2025-11-27 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_hr'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HR',
        ),
    ]
