# Generated by Django 4.2.26 on 2025-11-27 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_hrprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='hrprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='hr_profiles/'),
        ),
    ]
