# Generated by Django 5.2.8 on 2025-11-27 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_hrprofile_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='education_10th_percentage',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='education_12th_percentage',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='father_name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='mother_name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='pg_course',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='pg_percentage',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='phd_percentage',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='phd_topic',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='ug_course',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='ug_percentage',
        ),
    ]
