# Generated by Django 4.2.26 on 2025-11-27 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_remove_employee_education_10th_percentage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_date', models.DateField()),
                ('check_in_time', models.TimeField(blank=True, null=True)),
                ('check_out_time', models.TimeField(blank=True, null=True)),
                ('break_start_time', models.TimeField(blank=True, null=True)),
                ('break_end_time', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('half_day', 'Half Day'), ('leave', 'On Leave'), ('late', 'Late Arrival'), ('early_departure', 'Early Departure'), ('holiday', 'Holiday'), ('weekend', 'Weekend'), ('remote_work', 'Remote Work')], default='present', max_length=20)),
                ('shift_type', models.CharField(choices=[('morning', 'Morning Shift (9 AM - 6 PM)'), ('evening', 'Evening Shift (2 PM - 11 PM)'), ('night', 'Night Shift (11 PM - 8 AM)'), ('general', 'General Shift'), ('flexible', 'Flexible Timing'), ('full_time', 'Full Time'), ('part_time', 'Part Time')], default='morning', max_length=20)),
                ('total_worked_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('break_duration_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('overtime_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('check_in_location', models.CharField(blank=True, max_length=255, null=True)),
                ('check_out_location', models.CharField(blank=True, max_length=255, null=True)),
                ('device_info', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('approved_by', models.CharField(blank=True, max_length=200, null=True)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-attendance_date'],
            },
        ),
        migrations.CreateModel(
            name='LeaveApply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('annual', 'Annual Leave'), ('sick', 'Sick Leave'), ('casual', 'Casual Leave'), ('maternity', 'Maternity Leave'), ('paternity', 'Paternity Leave'), ('emergency', 'Emergency Leave'), ('unpaid', 'Unpaid Leave'), ('half_day', 'Half Day Leave'), ('compensatory', 'Compensatory Off'), ('work_from_home', 'Work From Home'), ('bereavement', 'Bereavement Leave'), ('study', 'Study Leave'), ('marriage', 'Marriage Leave'), ('medical', 'Medical Leave')], max_length=30)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_days', models.PositiveIntegerField()),
                ('half_day', models.BooleanField(default=False)),
                ('half_day_session', models.CharField(blank=True, choices=[('morning', 'Morning Session'), ('afternoon', 'Afternoon Session')], max_length=20, null=True)),
                ('reason', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('contact_details', models.CharField(blank=True, max_length=255, null=True)),
                ('emergency_contact', models.CharField(blank=True, max_length=255, null=True)),
                ('supporting_document', models.FileField(blank=True, null=True, upload_to='leave_documents/')),
                ('medical_certificate', models.FileField(blank=True, null=True, upload_to='leave_documents/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('revoked', 'Revoked')], default='pending', max_length=20)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.CharField(blank=True, max_length=200, null=True)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('manager_comments', models.TextField(blank=True, null=True)),
                ('hr_comments', models.TextField(blank=True, null=True)),
                ('tl_approved', models.BooleanField(default=False)),
                ('tl_approved_by', models.CharField(blank=True, max_length=200, null=True)),
                ('tl_approval_date', models.DateTimeField(blank=True, null=True)),
                ('tl_comments', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-applied_at'],
            },
        ),
        migrations.CreateModel(
            name='LeaveApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approver_type', models.CharField(choices=[('team_leader', 'Team Leader'), ('hr', 'HR Manager'), ('senior_manager', 'Senior Manager'), ('director', 'Director')], max_length=20)),
                ('approver_name', models.CharField(max_length=200)),
                ('approver_email', models.EmailField(max_length=254)),
                ('decision', models.CharField(choices=[('approve', 'Approve'), ('reject', 'Reject'), ('modify', 'Modify Request'), ('need_more_info', 'Need More Information'), ('escalate', 'Escalate to Higher Authority')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('modified', 'Modified'), ('escalated', 'Escalated')], default='pending', max_length=20)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('decision_date', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('modified_start_date', models.DateField(blank=True, null=True)),
                ('modified_end_date', models.DateField(blank=True, null=True)),
                ('modified_days', models.PositiveIntegerField(blank=True, null=True)),
                ('modified_reason', models.TextField(blank=True, null=True)),
                ('escalated_to', models.CharField(blank=True, max_length=200, null=True)),
                ('escalation_reason', models.TextField(blank=True, null=True)),
                ('escalated_date', models.DateTimeField(blank=True, null=True)),
                ('reminder_sent', models.BooleanField(default=False)),
                ('last_reminder_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='audience',
        ),
        migrations.AddField(
            model_name='announcement',
            name='acknowledged_by_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='announcement',
            name='acknowledgment_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='announcement',
            name='attachments',
            field=models.FileField(blank=True, null=True, upload_to='announcement_attachments/'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='author_department',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='author_designation',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='comments_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='compliance_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='announcement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='announcement_images/'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='keywords',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='likes_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='announcement',
            name='publish_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='read_by_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='announcement',
            name='shares_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='announcement',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('published', 'Published'), ('expired', 'Expired'), ('archived', 'Archived'), ('withdrawn', 'Withdrawn')], default='draft', max_length=15),
        ),
        migrations.AddField(
            model_name='announcement',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='announcement',
            name='target_audience',
            field=models.CharField(choices=[('all', 'All Employees'), ('management', 'Management Only'), ('department', 'Specific Departments'), ('location', 'Specific Locations'), ('contract_type', 'Contract Type Based'), ('role_based', 'Role Based')], default='all', max_length=30),
        ),
        migrations.AddField(
            model_name='announcement',
            name='target_departments',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='announcement',
            name='target_locations',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='announcement',
            name='target_roles',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='announcement',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='category',
            field=models.CharField(choices=[('company_news', 'Company News'), ('hr_updates', 'HR Updates'), ('policy_changes', 'Policy Changes'), ('events', 'Events'), ('general', 'General'), ('holiday', 'Holiday Notice'), ('training', 'Training & Development'), ('awards', 'Awards & Recognition'), ('technology', 'Technology Updates'), ('facilities', 'Facilities & Infrastructure'), ('safety', 'Safety & Security'), ('compliance', 'Compliance & Legal'), ('financial', 'Financial Updates'), ('product', 'Product Updates'), ('marketing', 'Marketing & Sales')], max_length=30),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='created_by',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical'), ('urgent', 'Urgent')], default='medium', max_length=10),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['category', 'priority'], name='app_announc_categor_b19bcf_idx'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['status', 'publish_date'], name='app_announc_status_fe75ff_idx'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['expiry_date'], name='app_announc_expiry__e7ce54_idx'),
        ),
        migrations.AddField(
            model_name='leaveapproval',
            name='leave_application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='app.leaveapply'),
        ),
        migrations.AddField(
            model_name='leaveapply',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_applications', to='app.employee'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='app.employee'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('employee', 'attendance_date')},
        ),
    ]
