# Generated by Django 4.2.26 on 2025-11-28 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_attendance_leaveapply_leaveapproval_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('delayed', 'Delayed'), ('cancelled', 'Cancelled')], default='planned', max_length=20)),
                ('planned_date', models.DateField()),
                ('actual_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completion_percentage', models.PositiveIntegerField(default=0)),
                ('deliverables', models.TextField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='app.projectassignment')),
                ('responsible_employees', models.ManyToManyField(related_name='milestone_responsibilities', to='app.employee')),
            ],
            options={
                'ordering': ['planned_date'],
            },
        ),
        migrations.CreateModel(
            name='ProjectTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('task_status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('in_review', 'In Review'), ('completed', 'Completed'), ('on_hold', 'On Hold'), ('cancelled', 'Cancelled')], default='not_started', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateTimeField()),
                ('due_date', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('estimated_hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('actual_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('progress_percentage', models.PositiveIntegerField(default=0)),
                ('milestone', models.CharField(blank=True, max_length=100, null=True)),
                ('quality_score', models.PositiveIntegerField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True, null=True)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to='app.teamleader')),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to='app.employee')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='app.projectassignment')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewed_tasks', to='app.teamleader')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project', 'assigned_to'], name='app_project_project_e7223b_idx'), models.Index(fields=['task_status', 'priority'], name='app_project_task_st_638407_idx'), models.Index(fields=['due_date'], name='app_project_due_dat_014f90_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProjectDiscussion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('message', 'Message'), ('update', 'Project Update'), ('question', 'Question'), ('task_assignment', 'Task Assignment'), ('completion_report', 'Completion Report'), ('issue', 'Issue/Problem'), ('suggestion', 'Suggestion'), ('status_report', 'Status Report')], default='message', max_length=20)),
                ('subject', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent'), ('critical', 'Critical')], default='normal', max_length=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed'), ('pending_review', 'Pending Review'), ('escalated', 'Escalated')], default='open', max_length=20)),
                ('is_announcement', models.BooleanField(default=False)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='project_discussions/')),
                ('attachment_name', models.CharField(blank=True, max_length=255, null=True)),
                ('task_due_date', models.DateTimeField(blank=True, null=True)),
                ('task_status', models.CharField(blank=True, max_length=50, null=True)),
                ('estimated_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('actual_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('completion_percentage', models.PositiveIntegerField(default=0)),
                ('milestone_reached', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_by', models.CharField(blank=True, max_length=200, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True, null=True)),
                ('parent_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='app.projectdiscussion')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussions', to='app.projectassignment')),
                ('receiver_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='app.employee')),
                ('receiver_tl', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_tl_messages', to='app.teamleader')),
                ('sender_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='app.employee')),
                ('sender_tl', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_tl_messages', to='app.teamleader')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project', 'created_at'], name='app_project_project_e40801_idx'), models.Index(fields=['sender_employee', 'created_at'], name='app_project_sender__9dce1d_idx'), models.Index(fields=['sender_tl', 'created_at'], name='app_project_sender__394b31_idx'), models.Index(fields=['status', 'priority'], name='app_project_status_fda2c9_idx'), models.Index(fields=['message_type'], name='app_project_message_8285be_idx')],
            },
        ),
    ]
