# Generated by Django 4.2.26 on 2025-11-28 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_projectmilestone_projecttask_projectdiscussion'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyAttendanceSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=20)),
                ('year', models.PositiveIntegerField()),
                ('total_working_days', models.PositiveIntegerField(default=0)),
                ('present_days', models.PositiveIntegerField(default=0)),
                ('absent_days', models.PositiveIntegerField(default=0)),
                ('half_days', models.PositiveIntegerField(default=0)),
                ('late_arrivals', models.PositiveIntegerField(default=0)),
                ('approved_leaves', models.PositiveIntegerField(default=0)),
                ('unpaid_leaves', models.PositiveIntegerField(default=0)),
                ('holiday_days', models.PositiveIntegerField(default=0)),
                ('weekend_days', models.PositiveIntegerField(default=0)),
                ('remote_work_days', models.PositiveIntegerField(default=0)),
                ('total_worked_hours', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('total_overtime_hours', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('salary_deduction_for_absences', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('salary_deduction_for_half_days', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('salary_deduction_for_late_arrivals', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('leave_encashment', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_finalized', models.BooleanField(default=False)),
                ('finalized_by', models.CharField(blank=True, max_length=200, null=True)),
                ('finalized_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_attendance', to='app.employee')),
            ],
            options={
                'ordering': ['-year', '-month'],
                'unique_together': {('employee', 'month', 'year')},
            },
        ),
        migrations.AddField(
            model_name='payroll',
            name='allowances',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payroll',
            name='gross_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payroll',
            name='half_day_deduction',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payroll',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payroll',
            name='late_arrival_deduction',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payroll',
            name='leave_deduction',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payroll',
            name='other_deductions',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payroll',
            name='overtime_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payroll',
            name='processed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payroll',
            name='professional_tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payroll',
            name='total_deductions',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payroll',
            name='year',
            field=models.PositiveIntegerField(default=2025),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='final_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='PayrollDeduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deduction_type', models.CharField(choices=[('absent', 'Absence Deduction'), ('half_day', 'Half Day Deduction'), ('late_arrival', 'Late Arrival Deduction'), ('unpaid_leave', 'Unpaid Leave Deduction'), ('leave_without_pay', 'Leave Without Pay'), ('misconduct', 'Misconduct Deduction'), ('advance_salary', 'Advance Salary Recovery'), ('loan_recovery', 'Loan Recovery'), ('pf', 'Provident Fund'), ('professional_tax', 'Professional Tax'), ('other', 'Other Deductions')], max_length=30)),
                ('description', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('calculation_basis', models.CharField(blank=True, max_length=100, null=True)),
                ('units_deducted', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('is_approved', models.BooleanField(default=True)),
                ('approved_by', models.CharField(blank=True, max_length=200, null=True)),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attendance_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.attendance')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.employee')),
                ('leave_application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.leaveapply')),
                ('monthly_summary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.monthlyattendancesummary')),
                ('payroll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deductions', to='app.payroll')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('modified', 'Modified')], default='pending', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('tl_comments', models.TextField(blank=True, null=True)),
                ('modified_check_in_time', models.TimeField(blank=True, null=True)),
                ('modified_check_out_time', models.TimeField(blank=True, null=True)),
                ('is_late_arrival', models.BooleanField(default=False)),
                ('late_minutes', models.PositiveIntegerField(default=0)),
                ('marked_as_half_day', models.BooleanField(default=False)),
                ('attendance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='approval', to='app.attendance')),
                ('team_leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_approvals', to='app.teamleader')),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
    ]
