# Generated by Django 4.2.26 on 2025-11-28 19:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_monthlyattendancesummary_payroll_allowances_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='can_check_out',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendance',
            name='check_in_reset_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='is_check_in_allowed',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='AttendanceCheckLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_type', models.CharField(choices=[('check_in', 'Check In'), ('check_out', 'Check Out'), ('check_in_denied', 'Check In Denied'), ('check_out_denied', 'Check Out Denied')], max_length=20)),
                ('check_time', models.DateTimeField()),
                ('attendance_date', models.DateField()),
                ('is_denied', models.BooleanField(default=False)),
                ('denial_reason', models.CharField(blank=True, choices=[('before_10_10_am', 'Check-in not allowed before 10:10 AM'), ('already_checked_in', 'Already checked in today'), ('already_checked_out', 'Already checked out today'), ('no_attendance_record', 'No attendance record found'), ('insufficient_hours', 'Insufficient worked hours for check-out'), ('weekend', 'Weekend - No check-in allowed'), ('holiday', 'Holiday - No check-in allowed'), ('other', 'Other reason')], max_length=50, null=True)),
                ('denial_message', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('device_info', models.CharField(blank=True, max_length=255, null=True)),
                ('worked_hours_at_check', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('official_start_time', models.TimeField(default=datetime.time(10, 45))),
                ('check_in_allowed_time', models.TimeField(default=datetime.time(10, 10))),
                ('required_work_hours', models.DecimalField(decimal_places=2, default=8.0, max_digits=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_logs', to='app.employee')),
            ],
            options={
                'ordering': ['-check_time'],
            },
        ),
        migrations.CreateModel(
            name='SalaryProcessing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary_month', models.CharField(max_length=20)),
                ('salary_year', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('processing_start_date', models.DateField()),
                ('processing_end_date', models.DateField()),
                ('gross_salary', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('net_salary', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('processed_by', models.CharField(blank=True, max_length=200, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('processed_date', models.DateField(blank=True, null=True)),
                ('is_within_processing_window', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_processings', to='app.employee')),
                ('monthly_summary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.monthlyattendancesummary')),
                ('payroll_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.payroll')),
            ],
            options={
                'ordering': ['-salary_year', '-salary_month'],
                'unique_together': {('employee', 'salary_month', 'salary_year')},
            },
        ),
    ]
