# Generated by Django 4.2.26 on 2025-11-29 12:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_attendance_can_check_out_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancechecklog',
            name='check_in_end_time',
            field=models.TimeField(default=datetime.time(10, 50)),
        ),
        migrations.AddField(
            model_name='attendancechecklog',
            name='check_out_end_time',
            field=models.TimeField(default=datetime.time(18, 45)),
        ),
        migrations.AddField(
            model_name='attendancechecklog',
            name='check_out_start_time',
            field=models.TimeField(default=datetime.time(18, 20)),
        ),
        migrations.AlterField(
            model_name='attendancechecklog',
            name='check_in_allowed_time',
            field=models.TimeField(default=datetime.time(10, 0)),
        ),
    ]
