# Generated by Django 4.2.26 on 2025-11-30 07:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_add_missing_attendance_check_log_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamChatSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_notifications', models.BooleanField(default=True)),
                ('push_notifications', models.BooleanField(default=True)),
                ('sound_notifications', models.BooleanField(default=True)),
                ('allow_direct_messages', models.BooleanField(default=True)),
                ('auto_reply_enabled', models.BooleanField(default=False)),
                ('auto_reply_message', models.TextField(blank=True, null=True)),
                ('working_hours_start', models.TimeField(default=datetime.time(9, 0))),
                ('working_hours_end', models.TimeField(default=datetime.time(18, 0))),
                ('working_days', models.JSONField(default=list)),
                ('auto_away_enabled', models.BooleanField(default=True)),
                ('auto_away_minutes', models.PositiveIntegerField(default=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team_assignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chat_settings', to='app.teamassignment')),
            ],
            options={
                'verbose_name': 'Team Chat Settings',
                'verbose_name_plural': 'Team Chat Settings',
            },
        ),
        migrations.CreateModel(
            name='TeamChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_type', models.CharField(choices=[('direct', 'Direct Message'), ('team', 'Team Message'), ('group', 'Group Message'), ('announcement', 'Team Announcement')], default='direct', max_length=20)),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('message', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('closed', 'Closed')], default='active', max_length=20)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='team_chat_attachments/')),
                ('attachment_name', models.CharField(blank=True, max_length=255, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('likes_count', models.PositiveIntegerField(default=0)),
                ('replies_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='app.teamchat')),
                ('receiver_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_team_chats', to='app.employee')),
                ('receiver_tl', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_team_chats', to='app.teamleader')),
                ('sender_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_team_chats', to='app.employee')),
                ('sender_tl', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_team_chats', to='app.teamleader')),
                ('team_assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_chats', to='app.teamassignment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PresentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_date', models.DateField()),
                ('marked_time', models.DateTimeField(auto_now_add=True)),
                ('check_in_time', models.TimeField(blank=True, null=True)),
                ('check_out_time', models.TimeField(blank=True, null=True)),
                ('work_details', models.TextField(blank=True, null=True)),
                ('late_marked', models.BooleanField(default=False)),
                ('marked_by', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='present_records', to='app.employee')),
            ],
            options={
                'ordering': ['-attendance_date'],
            },
        ),
        migrations.CreateModel(
            name='LateMarkRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_date', models.DateField()),
                ('marked_time', models.DateTimeField(auto_now_add=True)),
                ('actual_check_in_time', models.TimeField()),
                ('late_minutes', models.PositiveIntegerField()),
                ('reason', models.TextField(blank=True, null=True)),
                ('marked_by', models.CharField(blank=True, max_length=200, null=True)),
                ('approved', models.BooleanField(default=False)),
                ('approved_by', models.CharField(blank=True, max_length=200, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='late_mark_records', to='app.employee')),
            ],
            options={
                'ordering': ['-attendance_date'],
            },
        ),
        migrations.CreateModel(
            name='DailyWorkCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField()),
                ('office_closing_time', models.TimeField(default=datetime.time(18, 30))),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Work Completed'), ('partial', 'Partial Work'), ('not_completed', 'Not Completed'), ('extended', 'Extended Hours')], default='pending', max_length=20)),
                ('work_completion_time', models.DateTimeField(blank=True, null=True)),
                ('tasks_completed', models.TextField()),
                ('challenges_faced', models.TextField(blank=True, null=True)),
                ('tomorrow_plan', models.TextField(blank=True, null=True)),
                ('additional_notes', models.TextField(blank=True, null=True)),
                ('actual_work_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('overtime_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('submitted_to_tl', models.BooleanField(default=False)),
                ('tl_reviewed', models.BooleanField(default=False)),
                ('tl_reviewed_by', models.CharField(blank=True, max_length=200, null=True)),
                ('tl_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('tl_comments', models.TextField(blank=True, null=True)),
                ('submitted_to_hr', models.BooleanField(default=False)),
                ('hr_reviewed', models.BooleanField(default=False)),
                ('hr_reviewed_by', models.CharField(blank=True, max_length=200, null=True)),
                ('hr_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('hr_comments', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_work_completions', to='app.employee')),
            ],
            options={
                'ordering': ['-work_date'],
            },
        ),
        migrations.CreateModel(
            name='ChatReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction_type', models.CharField(choices=[('like', '👍 Like'), ('love', '❤️ Love'), ('laugh', '😄 Laugh'), ('angry', '😠 Angry'), ('sad', '😢 Sad'), ('thumbs_up', '👍 Thumbs Up'), ('thumbs_down', '👎 Thumbs Down'), ('celebrate', '🎉 Celebrate')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chat_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='app.teamchat')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_reactions', to='app.employee')),
                ('tl', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_reactions', to='app.teamleader')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AbsentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_date', models.DateField()),
                ('marked_time', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('marked_by', models.CharField(blank=True, max_length=200, null=True)),
                ('approved', models.BooleanField(default=False)),
                ('approved_by', models.CharField(blank=True, max_length=200, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absent_records', to='app.employee')),
            ],
            options={
                'ordering': ['-attendance_date'],
            },
        ),
        migrations.AddIndex(
            model_name='teamchat',
            index=models.Index(fields=['chat_type', 'status'], name='app_teamcha_chat_ty_5913f4_idx'),
        ),
        migrations.AddIndex(
            model_name='teamchat',
            index=models.Index(fields=['sender_employee', 'created_at'], name='app_teamcha_sender__38e1eb_idx'),
        ),
        migrations.AddIndex(
            model_name='teamchat',
            index=models.Index(fields=['sender_tl', 'created_at'], name='app_teamcha_sender__2b6434_idx'),
        ),
        migrations.AddIndex(
            model_name='teamchat',
            index=models.Index(fields=['receiver_employee', 'created_at'], name='app_teamcha_receive_f548c3_idx'),
        ),
        migrations.AddIndex(
            model_name='teamchat',
            index=models.Index(fields=['receiver_tl', 'created_at'], name='app_teamcha_receive_aa8c0f_idx'),
        ),
        migrations.AddIndex(
            model_name='teamchat',
            index=models.Index(fields=['created_at'], name='app_teamcha_created_2d99fc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='presentrecord',
            unique_together={('employee', 'attendance_date')},
        ),
        migrations.AlterUniqueTogether(
            name='latemarkrecord',
            unique_together={('employee', 'attendance_date')},
        ),
        migrations.AlterUniqueTogether(
            name='dailyworkcompletion',
            unique_together={('employee', 'work_date')},
        ),
        migrations.AlterUniqueTogether(
            name='chatreaction',
            unique_together={('chat_message', 'employee', 'tl')},
        ),
        migrations.AlterUniqueTogether(
            name='absentrecord',
            unique_together={('employee', 'attendance_date')},
        ),
    ]
